# Generated by Django 5.2.4 on 2025-08-08 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante_nome', models.CharField(max_length=100)),
                ('data_solicitacao', models.DateField(auto_now_add=True)),
                ('programar_para', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField()),
                ('aplicacao', models.CharField(blank=True, max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('especificacao', models.TextField(blank=True)),
                ('quantidade', models.IntegerField()),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='solicitacoes.solicitacao')),
            ],
        ),
    ]
