# Generated by Django 5.2.4 on 2025-08-09 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('fornecedor_nome', models.CharField(default='Fornecedor Não Informado', max_length=255)),
                ('fornecedor_cnpj_cpf', models.CharField(default='00000000000000', max_length=20)),
                ('fornecedor_endereco', models.CharField(default='Endereço Não Informado', max_length=255)),
                ('fornecedor_cidade', models.CharField(default='Cidade Desconhecida', max_length=100)),
                ('fornecedor_telefone', models.CharField(default='0000-0000', max_length=20)),
                ('local_entrega', models.CharField(default='Não Informado', max_length=255)),
                ('prazo_entrega', models.CharField(default='Não Informado', max_length=100)),
                ('centro_custo', models.CharField(default='Centro de Custo Não Informado', max_length=255)),
                ('condicao_pagamento', models.CharField(default='À vista', max_length=100)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('assinatura_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('assinatura_comprador', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(default='Item Não Informado', max_length=100)),
                ('descricao', models.CharField(default='Descrição Não Informada', max_length=255)),
                ('unidade', models.CharField(default='un', max_length=20)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedido')),
            ],
        ),
    ]
