# Generated by Django 5.2.4 on 2025-08-25 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
        ('solicitacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='solicitacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='solicitacoes.solicitacao'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
